name: DependencyCheck workshop
on: [ push ]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "* Build & Test *"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Check for vulnerabilities
        run: ./gradlew dependencyCheckAnalyze
        
